### Creates a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test"
}

### Signs in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test"
}

### Finds user by id
GET  http://localhost:3000/auth/2

### Finds all users with a specified email
GET  http://localhost:3000/

### Deletes user by id
DELETE  http://localhost:3000/auth/1

### Updates user by id
PATCH  http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "aaaa@aaaa.com"
}